/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './users.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './users.component';
const styles_UsersComponent:any[] = [i0.styles];
export const RenderType_UsersComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_UsersComponent,data:{}});
export function View_UsersComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['Users component']))],(null as any),(null as any));
}
export function View_UsersComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'ng-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_UsersComponent_0,
      RenderType_UsersComponent)),i1.ɵdid(49152,(null as any),0,i2.UsersComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const UsersComponentNgFactory:i1.ComponentFactory<i2.UsersComponent> = i1.ɵccf('ng-component',
    i2.UsersComponent,View_UsersComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovcHJvamVjdHMvanVhbi1kYXZpZC1zYW5jaGV6L3NyYy9hcHAvdXNlcnMvdXNlcnMuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L3Byb2plY3RzL2p1YW4tZGF2aWQtc2FuY2hlei9zcmMvYXBwL3VzZXJzL3VzZXJzLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L3Byb2plY3RzL2p1YW4tZGF2aWQtc2FuY2hlei9zcmMvYXBwL3VzZXJzL3VzZXJzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovcHJvamVjdHMvanVhbi1kYXZpZC1zYW5jaGV6L3NyYy9hcHAvdXNlcnMvdXNlcnMuY29tcG9uZW50LnRzLlVzZXJzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPlVzZXJzIGNvbXBvbmVudDwvaDE+IiwiPG5nLWNvbXBvbmVudD48L25nLWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBOzs7b0JDQUo7TUFBQTsrQkFBQSxVQUFBO01BQUE7OzsifQ==
