/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './users.module';
import * as i2 from './users.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/router';
import * as i5 from './users-routing.module';
import * as i6 from './users.component';
export const UsersModuleNgFactory:i0.NgModuleFactory<i1.UsersModule> = i0.ɵcmf(i1.UsersModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.UsersComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i3.NgLocalization,i3.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,
              i3.CommonModule,i3.CommonModule,([] as any[])),i0.ɵmpd(512,i4.RouterModule,
              i4.RouterModule,[[2,i4.ɵa],[2,i4.Router]]),i0.ɵmpd(512,i5.UsersRoutingModule,
              i5.UsersRoutingModule,([] as any[])),i0.ɵmpd(512,i1.UsersModule,i1.UsersModule,
              ([] as any[])),i0.ɵmpd(1024,i4.ROUTES,() => {
            return [[{path:'',component:i6.UsersComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovcHJvamVjdHMvanVhbi1kYXZpZC1zYW5jaGV6L3NyYy9hcHAvdXNlcnMvdXNlcnMubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L3Byb2plY3RzL2p1YW4tZGF2aWQtc2FuY2hlei9zcmMvYXBwL3VzZXJzL3VzZXJzLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
