/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/router';
import * as i3 from '@angular/common';
import * as i4 from './app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['Hello World!'])),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),0,'hr',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),2,'a',[['routerLink',
          '/']],[[1,'target',0],[8,'href',4]],[[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        if (('click' === en)) {
          const pd_0:any = ((<any>i1.ɵnov(_v,6).onClick($event.button,$event.ctrlKey,
              $event.metaKey,$event.shiftKey)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),i1.ɵdid(671744,(null as any),0,i2.RouterLinkWithHref,
          [i2.Router,i2.ActivatedRoute,i3.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),(_l()(),i1.ɵted((null as any),['Home'])),(_l()(),i1.ɵted((null as any),
          ['\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),2,'a',[['routerLink',
          '/users']],[[1,'target',0],[8,'href',4]],[[(null as any),'click']],(_v,en,
          $event) => {
        var ad:boolean = true;
        if (('click' === en)) {
          const pd_0:any = ((<any>i1.ɵnov(_v,10).onClick($event.button,$event.ctrlKey,
              $event.metaKey,$event.shiftKey)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),i1.ɵdid(671744,(null as any),0,i2.RouterLinkWithHref,
          [i2.Router,i2.ActivatedRoute,i3.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),(_l()(),i1.ɵted((null as any),['Users'])),(_l()(),i1.ɵted((null as any),
          ['\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),0,'hr',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(16777216,(null as any),
          (null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),i1.ɵdid(212992,(null as any),
          0,i2.RouterOutlet,[i2.ChildrenOutletContexts,i1.ViewContainerRef,i1.ComponentFactoryResolver,
              [8,(null as any)],i1.ChangeDetectorRef],(null as any),(null as any))],
      (_ck,_v) => {
        const currVal_2:any = '/';
        _ck(_v,6,0,currVal_2);
        const currVal_5:any = '/users';
        _ck(_v,10,0,currVal_5);
        _ck(_v,16,0);
      },(_ck,_v) => {
        const currVal_0:any = i1.ɵnov(_v,6).target;
        const currVal_1:any = i1.ɵnov(_v,6).href;
        _ck(_v,5,0,currVal_0,currVal_1);
        const currVal_3:any = i1.ɵnov(_v,10).target;
        const currVal_4:any = i1.ɵnov(_v,10).href;
        _ck(_v,9,0,currVal_3,currVal_4);
      });
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(49152,(null as any),0,i4.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i4.AppComponent> = i1.ɵccf('app-root',
    i4.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovcHJvamVjdHMvanVhbi1kYXZpZC1zYW5jaGV6L3NyYy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9wcm9qZWN0cy9qdWFuLWRhdmlkLXNhbmNoZXovc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovcHJvamVjdHMvanVhbi1kYXZpZC1zYW5jaGV6L3NyYy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovcHJvamVjdHMvanVhbi1kYXZpZC1zYW5jaGV6L3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aDE+SGVsbG8gV29ybGQhPC9oMT5cclxuPGhyPlxyXG48YSByb3V0ZXJMaW5rPVwiL1wiPkhvbWU8L2E+XHJcbjxhIHJvdXRlckxpbms9XCIvdXNlcnNcIj5Vc2VyczwvYT5cclxuPGhyPlxyXG48cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+IiwiPGFwcC1yb290PjwvYXBwLXJvb3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBLGtDQUFpQjtNQUNyQjtVQUFBLDBEQUFJO1VBQUEsU0FDSjtVQUFBO1FBQUE7UUFBQTtVQUFBO2NBQUE7VUFBQTtRQUFBO1FBQUE7TUFBQSx1Q0FBQTtVQUFBO1VBQUEsZUFBa0IseUNBQVE7VUFBQSxTQUMxQjtVQUFBO2dCQUFBO1FBQUE7UUFBQTtVQUFBO2NBQUE7VUFBQTtRQUFBO1FBQUE7TUFBQSx1Q0FBQTtVQUFBO1VBQUEsZUFBdUIsMENBQVM7VUFBQSxTQUNoQztVQUFBO01BQUksdUNBQ0o7VUFBQTtVQUFBLG1EQUFBO1VBQUE7Y0FBQTs7UUFIRztRQUFILFdBQUcsU0FBSDtRQUNHO1FBQUgsWUFBRyxTQUFIO1FBRUE7O1FBSEE7UUFBQTtRQUFBLFdBQUEsbUJBQUE7UUFDQTtRQUFBO1FBQUEsV0FBQSxtQkFBQTs7OztvQkNIQTtNQUFBO2FBQUE7Ozs7In0=
